### ISSUE TITLE
replicating admin functionality with an EditTable

### ISSUE THREAD

**Issue by martindemello** [iommirocks/iommi#291]
For the following two models:

```
Player:
   name = CharField()

Entrant:
  division = ForeignKey(Division)
  player = ForeignKey(Player)
```

The django admin panel gives me a pretty nice interface to manage the `Entrants` table, with a table of `Entrant`s, and an `Add Entrant` button which pulls up a form where the `Player` field contains both a dropdown field and an `Add Player` button, so that I can add a new `Player` and create an `Entrant` linked to the new `Player` in one go.

Is there a way I can replicate this easily within iommi?

**Comment by boxed** [comment]
The add form isn't in the iommi admin right now. We would be open to PRs. I would think adding a link to the corresponding add page would be a good place to start.

**Comment by friedgit** [comment]
I have another scenario where I think I would like to use an EditTable instead of a Table in the iommi admin. 

n players competed in a race and each was awarded a score. These players need to be ranked for the next round of the competition. Where the players scores are all different, the ranking is simply determined by the scores, but where some players have equal scores, tie breaking rules need to be applied and the ranks assigned by an administrator of the competition. 

In the django admin a column can be made editable directly in the list display table using list_editable, and that is what I would like to do in the iommi admin, probably with an EditTable, if that were feasible. I also need to be able to initiate an action to confirm a change of rank, and once confirmed, to shuffle other ranks upwards to replace the players's old rank, and / or downwards from the insertion point of the new rank. 

I would prefer to be able to do this on the table directly without needing to follow an edit link to a new form focused on the player's individual record.

I will open a separate PR if you prefer.

**Comment by boxed** [comment]
I mean.. I like the idea of being able to have EditTable features on the admin, but your situation sounds like maybe you want to take a step back and make a better GUI than just a bunch of numbers in a column. Those tie breaking rules for example, can't the computer handle those?

**Comment by friedgit** [comment]
> Those tie breaking rules for example, can't the computer handle those?

I actually asked the same question, but my domain expert says no, not in the first instance anyway - the rules vary according to the type of event and can be very arcane. I have a solution now using the Django admin using formsets.

**Comment by boxed** [comment]
Arcane rules seem like exactly what you want a computer to do and not a human 🤣

**Comment by boxed** [comment]
This is coming in #525
